import { Talent } from './types';

// Use valid WoW icon names from zamimg CDN
const getIcon = (iconName: string) => `https://wow.zamimg.com/images/wow/icons/large/${iconName}.jpg`;

export const ARMS_TALENTS: Talent[] = [
  // ROW 0 (Requires 0 points)
  {
    id: 'improved_heroic_strike',
    name: 'Improved Heroic Strike',
    icon: getIcon('ability_rogue_ambush'),
    row: 0,
    col: 0,
    maxRank: 3,
    currentRank: 0,
    description: [
      "Reduces the cost of your Heroic Strike ability by 1 rage point.",
      "Reduces the cost of your Heroic Strike ability by 2 rage points.",
      "Reduces the cost of your Heroic Strike ability by 3 rage points."
    ]
  },
  {
    id: 'deflection',
    name: 'Deflection',
    icon: getIcon('ability_parry'),
    row: 0,
    col: 1,
    maxRank: 5,
    currentRank: 0,
    description: [
      "Increases your Parry chance by 1%.",
      "Increases your Parry chance by 2%.",
      "Increases your Parry chance by 3%.",
      "Increases your Parry chance by 4%.",
      "Increases your Parry chance by 5%."
    ]
  },
  {
    id: 'improved_rend',
    name: 'Improved Rend',
    icon: getIcon('ability_gouge'),
    row: 0,
    col: 2,
    maxRank: 3,
    currentRank: 0,
    description: [
      "Increases the bleed damage done by your Rend ability by 15%.",
      "Increases the bleed damage done by your Rend ability by 25%.",
      "Increases the bleed damage done by your Rend ability by 35%."
    ]
  },

  // ROW 1 (Requires 5 points)
  {
    id: 'improved_charge',
    name: 'Improved Charge',
    icon: getIcon('ability_warrior_charge'),
    row: 1,
    col: 0,
    maxRank: 2,
    currentRank: 0,
    description: [
      "Increases the amount of rage generated by your Charge ability by 3.",
      "Increases the amount of rage generated by your Charge ability by 6."
    ]
  },
  {
    id: 'tactical_mastery',
    name: 'Tactical Mastery',
    icon: getIcon('spell_nature_enchantarmor'),
    row: 1,
    col: 1,
    maxRank: 5,
    currentRank: 0,
    description: [
      "You retain up to 5 of your rage points when you change stances.",
      "You retain up to 10 of your rage points when you change stances.",
      "You retain up to 15 of your rage points when you change stances.",
      "You retain up to 20 of your rage points when you change stances.",
      "You retain up to 25 of your rage points when you change stances."
    ]
  },
  {
    id: 'improved_thunder_clap',
    name: 'Imp. Thunder Clap',
    icon: getIcon('spell_nature_thunderclap'),
    row: 1,
    col: 3, // Far right
    maxRank: 3,
    currentRank: 0,
    description: [
      "Reduces the cost of your Thunder Clap ability by 1 rage point.",
      "Reduces the cost of your Thunder Clap ability by 2 rage points.",
      "Reduces the cost of your Thunder Clap ability by 4 rage points."
    ]
  },

  // ROW 2 (Requires 10 points)
  {
    id: 'improved_overpower',
    name: 'Imp. Overpower',
    icon: getIcon('inv_sword_05'),
    row: 2,
    col: 0,
    maxRank: 2,
    currentRank: 0,
    description: [
      "Increases the critical strike chance of your Overpower ability by 25%.",
      "Increases the critical strike chance of your Overpower ability by 50%."
    ]
  },
  {
    id: 'anger_management',
    name: 'Anger Management',
    icon: getIcon('spell_holy_blessingofstamina'),
    row: 2,
    col: 1,
    maxRank: 1,
    currentRank: 0,
    prerequisite: 'tactical_mastery', // Dependency
    description: [
      "Generates 1 rage every 3 seconds."
    ]
  },
  {
    id: 'deep_wounds',
    name: 'Deep Wounds',
    icon: getIcon('ability_backstab'),
    row: 2,
    col: 2,
    maxRank: 3,
    currentRank: 0,
    prerequisite: 'improved_rend', // Dependency
    description: [
      "Your critical strikes cause the opponent to bleed, dealing 20% of your melee weapon's average damage over 12 sec.",
      "Your critical strikes cause the opponent to bleed, dealing 40% of your melee weapon's average damage over 12 sec.",
      "Your critical strikes cause the opponent to bleed, dealing 60% of your melee weapon's average damage over 12 sec."
    ]
  },

  // ROW 3 (Requires 15 points)
  {
    id: 'two_handed_spec',
    name: '2H Wpn Specialization',
    icon: getIcon('inv_axe_09'),
    row: 3,
    col: 1,
    maxRank: 5,
    currentRank: 0,
    description: [
      "Increases the damage you deal with Two-Handed Melee Weapons by 1%.",
      "Increases the damage you deal with Two-Handed Melee Weapons by 2%.",
      "Increases the damage you deal with Two-Handed Melee Weapons by 3%.",
      "Increases the damage you deal with Two-Handed Melee Weapons by 4%.",
      "Increases the damage you deal with Two-Handed Melee Weapons by 5%."
    ]
  },
  {
    id: 'impale',
    name: 'Impale',
    icon: getIcon('ability_searingarrow'),
    row: 3,
    col: 2,
    maxRank: 2,
    currentRank: 0,
    prerequisite: 'deep_wounds',
    description: [
      "Increases the critical strike damage bonus of your abilities in Battle, Defensive, and Berserker stance by 10%.",
      "Increases the critical strike damage bonus of your abilities in Battle, Defensive, and Berserker stance by 20%."
    ]
  },

  // ROW 4 (Requires 20 points) - Just one for demo depth
  {
    id: 'axe_specialization',
    name: 'Axe Specialization',
    icon: getIcon('inv_axe_06'),
    row: 4,
    col: 0,
    maxRank: 5,
    currentRank: 0,
    description: [
      "Increases your chance to get a critical strike with Axes and Polearms by 1%.",
      "Increases your chance to get a critical strike with Axes and Polearms by 2%.",
      "Increases your chance to get a critical strike with Axes and Polearms by 3%.",
      "Increases your chance to get a critical strike with Axes and Polearms by 4%.",
      "Increases your chance to get a critical strike with Axes and Polearms by 5%."
    ]
  },
  {
    id: 'sweeping_strikes',
    name: 'Sweeping Strikes',
    icon: getIcon('ability_rogue_sliceanddice'),
    row: 4,
    col: 1,
    maxRank: 1,
    currentRank: 0,
    description: [
      "Your next 5 melee attacks strike an additional nearby opponent."
    ]
  },
  {
    id: 'mace_specialization',
    name: 'Mace Specialization',
    icon: getIcon('inv_mace_01'),
    row: 4,
    col: 2,
    maxRank: 5,
    currentRank: 0,
    description: [
      "Chance to stun target for 3 sec with a Mace.",
      "Chance to stun target for 3 sec with a Mace.",
      "Chance to stun target for 3 sec with a Mace.",
      "Chance to stun target for 3 sec with a Mace.",
      "Chance to stun target for 3 sec with a Mace."
    ]
  },
  {
    id: 'sword_specialization',
    name: 'Sword Specialization',
    icon: getIcon('inv_sword_27'),
    row: 4,
    col: 3,
    maxRank: 5,
    currentRank: 0,
    description: [
      "Chance to get an extra attack on the same target with a Sword.",
      "Chance to get an extra attack on the same target with a Sword.",
      "Chance to get an extra attack on the same target with a Sword.",
      "Chance to get an extra attack on the same target with a Sword.",
      "Chance to get an extra attack on the same target with a Sword."
    ]
  },
    // ROW 6 (Ultimate)
    {
    id: 'mortal_strike',
    name: 'Mortal Strike',
    icon: getIcon('ability_warrior_savageblow'),
    row: 6,
    col: 1,
    maxRank: 1,
    currentRank: 0,
    prerequisite: 'sweeping_strikes',
    description: [
      "A vicious strike that deals weapon damage plus 85 and wounds the target, reducing the effectiveness of any healing by 50% for 10 sec."
    ]
  }
];

export const FURY_TALENTS: Talent[] = [
  // ROW 0
  {
    id: 'booming_voice',
    name: 'Booming Voice',
    icon: getIcon('spell_nature_purge'),
    row: 0,
    col: 1,
    maxRank: 5,
    currentRank: 0,
    description: [
      "Increases the area of effect and duration of your Battle Shout and Demoralizing Shout by 10%.",
      "Increases the area of effect and duration of your Battle Shout and Demoralizing Shout by 20%.",
      "Increases the area of effect and duration of your Battle Shout and Demoralizing Shout by 30%.",
      "Increases the area of effect and duration of your Battle Shout and Demoralizing Shout by 40%.",
      "Increases the area of effect and duration of your Battle Shout and Demoralizing Shout by 50%."
    ]
  },
  {
    id: 'cruelty',
    name: 'Cruelty',
    icon: getIcon('ability_rogue_eviscerate'),
    row: 0,
    col: 2,
    maxRank: 5,
    currentRank: 0,
    description: [
      "Increases your chance to get a critical strike with melee weapons by 1%.",
      "Increases your chance to get a critical strike with melee weapons by 2%.",
      "Increases your chance to get a critical strike with melee weapons by 3%.",
      "Increases your chance to get a critical strike with melee weapons by 4%.",
      "Increases your chance to get a critical strike with melee weapons by 5%."
    ]
  },

  // ROW 1
  {
    id: 'improved_demoralizing_shout',
    name: 'Imp. Demoralizing Shout',
    icon: getIcon('ability_warrior_waracry'),
    row: 1,
    col: 1,
    maxRank: 5,
    currentRank: 0,
    description: [
      "Increases the melee attack power reduction of your Demoralizing Shout by 8%.",
      "Increases the melee attack power reduction of your Demoralizing Shout by 16%.",
      "Increases the melee attack power reduction of your Demoralizing Shout by 24%.",
      "Increases the melee attack power reduction of your Demoralizing Shout by 32%.",
      "Increases the melee attack power reduction of your Demoralizing Shout by 40%."
    ]
  },
  {
    id: 'unbridled_wrath',
    name: 'Unbridled Wrath',
    icon: getIcon('spell_nature_stoneclawtotem'),
    row: 1,
    col: 2,
    maxRank: 5,
    currentRank: 0,
    description: [
      "Gives you a 8% chance to generate an additional rage point when you deal melee damage with a weapon.",
      "Gives you a 16% chance to generate an additional rage point when you deal melee damage with a weapon.",
      "Gives you a 24% chance to generate an additional rage point when you deal melee damage with a weapon.",
      "Gives you a 32% chance to generate an additional rage point when you deal melee damage with a weapon.",
      "Gives you a 40% chance to generate an additional rage point when you deal melee damage with a weapon."
    ]
  },

  // ROW 2
  {
    id: 'improved_cleave',
    name: 'Improved Cleave',
    icon: getIcon('ability_warrior_cleave'),
    row: 2,
    col: 0,
    maxRank: 3,
    currentRank: 0,
    description: [
      "Increases the bonus damage done by your Cleave ability by 40%.",
      "Increases the bonus damage done by your Cleave ability by 80%.",
      "Increases the bonus damage done by your Cleave ability by 120%."
    ]
  },
  {
    id: 'piercing_howl',
    name: 'Piercing Howl',
    icon: getIcon('spell_shadow_deathscream'),
    row: 2,
    col: 1,
    maxRank: 1,
    currentRank: 0,
    description: [
      "Causes all enemies near the warrior to be dazed, reducing movement speed by 50% for 6 sec."
    ]
  },
  {
    id: 'blood_craze',
    name: 'Blood Craze',
    icon: getIcon('spell_shadow_summonimp'),
    row: 2,
    col: 2,
    maxRank: 3,
    currentRank: 0,
    description: [
      "Regenerates 1% of your total Health over 6 sec after being the victim of a critical strike.",
      "Regenerates 2% of your total Health over 6 sec after being the victim of a critical strike.",
      "Regenerates 3% of your total Health over 6 sec after being the victim of a critical strike."
    ]
  },
  {
    id: 'improved_battle_shout',
    name: 'Imp. Battle Shout',
    icon: getIcon('ability_warrior_battleshout'),
    row: 2,
    col: 3,
    maxRank: 5,
    currentRank: 0,
    description: [
      "Increases the melee attack power bonus of your Battle Shout by 5%.",
      "Increases the melee attack power bonus of your Battle Shout by 10%.",
      "Increases the melee attack power bonus of your Battle Shout by 15%.",
      "Increases the melee attack power bonus of your Battle Shout by 20%.",
      "Increases the melee attack power bonus of your Battle Shout by 25%."
    ]
  },

  // ROW 3
  {
    id: 'dual_wield_specialization',
    name: 'Dual Wield Spec',
    icon: getIcon('ability_dualwield'),
    row: 3,
    col: 0,
    maxRank: 5,
    currentRank: 0,
    description: [
      "Increases the damage done by your offhand weapon by 5%.",
      "Increases the damage done by your offhand weapon by 10%.",
      "Increases the damage done by your offhand weapon by 15%.",
      "Increases the damage done by your offhand weapon by 20%.",
      "Increases the damage done by your offhand weapon by 25%."
    ]
  },
  {
    id: 'improved_execute',
    name: 'Improved Execute',
    icon: getIcon('inv_sword_48'),
    row: 3,
    col: 1,
    maxRank: 2,
    currentRank: 0,
    description: [
      "Reduces the rage cost of your Execute ability by 2.",
      "Reduces the rage cost of your Execute ability by 5."
    ]
  },
  {
    id: 'enrage',
    name: 'Enrage',
    icon: getIcon('spell_shadow_unholyfrenzy'),
    row: 3,
    col: 2,
    maxRank: 5,
    currentRank: 0,
    description: [
      "Gives you a 5% melee damage bonus for 12 sec after being the victim of a critical strike.",
      "Gives you a 10% melee damage bonus for 12 sec after being the victim of a critical strike.",
      "Gives you a 15% melee damage bonus for 12 sec after being the victim of a critical strike.",
      "Gives you a 20% melee damage bonus for 12 sec after being the victim of a critical strike.",
      "Gives you a 25% melee damage bonus for 12 sec after being the victim of a critical strike."
    ]
  },

  // ROW 4
  {
    id: 'improved_slam',
    name: 'Improved Slam',
    icon: getIcon('ability_warrior_decisivestrike'),
    row: 4,
    col: 0,
    maxRank: 2,
    currentRank: 0,
    description: [
      "Decreases the casting time of your Slam ability by 0.5 sec.",
      "Decreases the casting time of your Slam ability by 1 sec."
    ]
  },
  {
    id: 'death_wish',
    name: 'Death Wish',
    icon: getIcon('spell_shadow_deathpact'),
    row: 4,
    col: 1,
    maxRank: 1,
    currentRank: 0,
    // Note: Some versions list Imp Exec as req, but usually it's tied to tree position. 
    // Classic wowhead calculator says no prereq link line.
    description: [
      "When activated, increases your physical damage by 20% and makes you immune to Fear effects, but lowers your armor and all resistances by 20%. Lasts 30 sec."
    ]
  },
  {
    id: 'improved_intercept',
    name: 'Imp. Intercept',
    icon: getIcon('ability_rogue_sprint'),
    row: 4,
    col: 3,
    maxRank: 2,
    currentRank: 0,
    description: [
      "Reduces the cooldown of your Intercept ability by 5 sec.",
      "Reduces the cooldown of your Intercept ability by 10 sec."
    ]
  },

  // ROW 5
  {
    id: 'berserker_rage',
    name: 'Improved Berserker Rage',
    icon: getIcon('spell_nature_ancestralguardian'),
    row: 5,
    col: 0,
    maxRank: 2,
    currentRank: 0,
    description: [
      "The Berserker Rage ability will generate 5 rage when used.",
      "The Berserker Rage ability will generate 10 rage when used."
    ]
  },
  {
    id: 'flurry',
    name: 'Flurry',
    icon: getIcon('ability_ghoulfrenzy'),
    row: 5,
    col: 2,
    maxRank: 5,
    currentRank: 0,
    prerequisite: 'enrage',
    description: [
      "Increases your attack speed by 10% for your next 3 swings after dealing a melee critical strike.",
      "Increases your attack speed by 15% for your next 3 swings after dealing a melee critical strike.",
      "Increases your attack speed by 20% for your next 3 swings after dealing a melee critical strike.",
      "Increases your attack speed by 25% for your next 3 swings after dealing a melee critical strike.",
      "Increases your attack speed by 30% for your next 3 swings after dealing a melee critical strike."
    ]
  },

  // ROW 6
  {
    id: 'bloodthirst',
    name: 'Bloodthirst',
    icon: getIcon('spell_nature_bloodlust'),
    row: 6,
    col: 1,
    maxRank: 1,
    currentRank: 0,
    prerequisite: 'death_wish',
    description: [
      "Instantly attack the target causing damage equal to 45% of your attack power.  In addition, the next 5 successful melee attacks will restore 10 health.  This effect lasts 8 sec."
    ]
  }
];